### ISSUE TITLE
Doest it need to install package ctags first?

### ISSUE THREAD

**Issue by chenyangguang** [ivalkeen/vim-ctrlp-tjump#23]
Doest it need to install package ctags first? Then vim-ctrlp-tjump should work?

**Comment by ivalkeen** [comment]
One of the prerequisites for `vim-ctrlp-tjump` to work is a working setup of vim with tags support. The plugin doesn't care how tags were produced (for example, I don't use ctags, but use [ripper-tags](https://github.com/tmm1/ripper-tags) instead) and relies purely on vim built-in functions to work with tags. 

You can find more information on how to set up vim to work with tags [here](http://vim.wikia.com/wiki/Browsing_programs_with_tags).

**Comment by chenyangguang** [comment]
Thanks
